# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/yli/desktop/hdr_ip/managed_ip_project/managed_ip_project.tmp/hdr_ip_v1_0_new1/hdr_ip_v1_0_new1.cache/wt [current_project]
set_property parent.project_path c:/users/yli/desktop/hdr_ip/managed_ip_project/managed_ip_project.tmp/hdr_ip_v1_0_new1/hdr_ip_v1_0_new1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths c:/Users/yli/Desktop/hdr_ip/ip_repo/hdr_ip_1.0 [current_project]
read_verilog -library xil_defaultlib c:/users/yli/desktop/hdr_ip/ip_repo/hdr_ip_1.0/hdl/hdr_ip_v1_0.v
synth_design -top hdr_ip_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef hdr_ip_v1_0.dcp
catch { report_utilization -file hdr_ip_v1_0_utilization_synth.rpt -pb hdr_ip_v1_0_utilization_synth.pb }
