# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.cache/wt [current_project]
set_property parent.project_path C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths C:/Users/yli/Desktop/hdr_complete_final_test/test/board_files [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_repo_paths {
  c:/Users/yli/Desktop/hdr_complete_final_test/test/video_to_axis
  c:/Users/yli/Desktop/edge_ip/edge_ip
  c:/Users/yli/Desktop/hdr_complete_final_test/test/hdr_ip_sof_fix
} [current_project]
add_files C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ddr_dma_v2.bd
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_0/ddr_dma_v2_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_0/ddr_dma_v2_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_0/ddr_dma_v2_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_v10_0/ddr_dma_v2_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_v10_0/ddr_dma_v2_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_v10_0/ddr_dma_v2_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_v10_0/ddr_dma_v2_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_bram_if_cntlr_0/ddr_dma_v2_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_bram_if_cntlr_0/ddr_dma_v2_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_lmb_bram_0/ddr_dma_v2_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_intc_0/ddr_dma_v2_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_intc_0/ddr_dma_v2_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_intc_0/ddr_dma_v2_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_mdm_1_0/ddr_dma_v2_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_mdm_1_0/ddr_dma_v2_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_clk_wiz_1_0/ddr_dma_v2_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_clk_wiz_1_0/ddr_dma_v2_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_clk_wiz_1_0/ddr_dma_v2_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_rst_clk_wiz_1_100M_0/ddr_dma_v2_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_rst_clk_wiz_1_100M_0/ddr_dma_v2_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_rst_clk_wiz_1_100M_0/ddr_dma_v2_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_mig_7series_0_0/ddr_dma_v2_mig_7series_0_0/user_design/constraints/ddr_dma_v2_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_mig_7series_0_0/ddr_dma_v2_mig_7series_0_0/user_design/constraints/ddr_dma_v2_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_mig_7series_0_0/ddr_dma_v2_mig_7series_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_uartlite_0_0/ddr_dma_v2_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_uartlite_0_0/ddr_dma_v2_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_uartlite_0_0/ddr_dma_v2_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_xbar_0/ddr_dma_v2_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_rst_mig_7series_0_81M_0/ddr_dma_v2_rst_mig_7series_0_81M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_rst_mig_7series_0_81M_0/ddr_dma_v2_rst_mig_7series_0_81M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_rst_mig_7series_0_81M_0/ddr_dma_v2_rst_mig_7series_0_81M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_dma_0_0/ddr_dma_v2_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_dma_0_0/ddr_dma_v2_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_dma_0_0/ddr_dma_v2_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_tft_0_0/ddr_dma_v2_axi_tft_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_tft_0_0/ddr_dma_v2_axi_tft_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_tft_0_0/ddr_dma_v2_axi_tft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_v_gamma_0_0/ddr_dma_v2_v_gamma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_v_gamma_0_0/ddr_dma_v2_v_gamma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_v_rgb2ycrcb_0_0/ddr_dma_v2_v_rgb2ycrcb_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_v_rgb2ycrcb_0_0/ddr_dma_v2_v_rgb2ycrcb_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_0/ddr_dma_v2_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_0/ddr_dma_v2_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_0/ddr_dma_v2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_cc_0/ddr_dma_v2_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_cc_0/ddr_dma_v2_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_1/ddr_dma_v2_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_1/ddr_dma_v2_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_1/ddr_dma_v2_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_2/ddr_dma_v2_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_2/ddr_dma_v2_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_2/ddr_dma_v2_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_3/ddr_dma_v2_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_3/ddr_dma_v2_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_3/ddr_dma_v2_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_4/ddr_dma_v2_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_4/ddr_dma_v2_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_4/ddr_dma_v2_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_5/ddr_dma_v2_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_0/ddr_dma_v2_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_0/ddr_dma_v2_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_1/ddr_dma_v2_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_1/ddr_dma_v2_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_2/ddr_dma_v2_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_2/ddr_dma_v2_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_3/ddr_dma_v2_auto_us_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_3/ddr_dma_v2_auto_us_3_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ddr_dma_v2_ooc.xdc]
set_property is_locked true [get_files C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/ddr_dma_v2.bd]

read_verilog -library xil_defaultlib C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/sources_1/bd/ddr_dma_v2/hdl/ddr_dma_v2_wrapper.v
read_xdc C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/constrs_1/new/vga_pins.xdc
set_property used_in_implementation false [get_files C:/Users/yli/Desktop/hdr_complete_final_test/test/temp/ddr_dma_v2.srcs/constrs_1/new/vga_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top ddr_dma_v2_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef ddr_dma_v2_wrapper.dcp
catch { report_utilization -file ddr_dma_v2_wrapper_utilization_synth.rpt -pb ddr_dma_v2_wrapper_utilization_synth.pb }
