# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_pins.xdc

# Block Designs: bd/ddr_dma_v2/ddr_dma_v2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2 || ORIG_REF_NAME==ddr_dma_v2}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_0/ddr_dma_v2_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_microblaze_0_0 || ORIG_REF_NAME==ddr_dma_v2_microblaze_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_v10_0/ddr_dma_v2_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_dlmb_v10_0 || ORIG_REF_NAME==ddr_dma_v2_dlmb_v10_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_v10_0/ddr_dma_v2_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_ilmb_v10_0 || ORIG_REF_NAME==ddr_dma_v2_ilmb_v10_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_bram_if_cntlr_0/ddr_dma_v2_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ddr_dma_v2_dlmb_bram_if_cntlr_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_bram_if_cntlr_0/ddr_dma_v2_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ddr_dma_v2_ilmb_bram_if_cntlr_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_lmb_bram_0/ddr_dma_v2_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_lmb_bram_0 || ORIG_REF_NAME==ddr_dma_v2_lmb_bram_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_periph_0/ddr_dma_v2_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ddr_dma_v2_microblaze_0_axi_periph_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_intc_0/ddr_dma_v2_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==ddr_dma_v2_microblaze_0_axi_intc_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_xlconcat_0/ddr_dma_v2_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_microblaze_0_xlconcat_0 || ORIG_REF_NAME==ddr_dma_v2_microblaze_0_xlconcat_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_mdm_1_0/ddr_dma_v2_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_mdm_1_0 || ORIG_REF_NAME==ddr_dma_v2_mdm_1_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_clk_wiz_1_0/ddr_dma_v2_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_clk_wiz_1_0 || ORIG_REF_NAME==ddr_dma_v2_clk_wiz_1_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_clk_wiz_1_100M_0/ddr_dma_v2_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ddr_dma_v2_rst_clk_wiz_1_100M_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_mig_7series_0_0/ddr_dma_v2_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_mig_7series_0_0 || ORIG_REF_NAME==ddr_dma_v2_mig_7series_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_uartlite_0_0/ddr_dma_v2_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_uartlite_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_uartlite_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_xbar_0/ddr_dma_v2_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_xbar_0 || ORIG_REF_NAME==ddr_dma_v2_xbar_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_mig_7series_0_81M_0/ddr_dma_v2_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==ddr_dma_v2_rst_mig_7series_0_81M_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_dma_0_0/ddr_dma_v2_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_dma_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_dma_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_tft_0_0/ddr_dma_v2_axi_tft_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_tft_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_tft_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_quad_spi_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_quad_spi_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_video_to_axis_0_0/ddr_dma_v2_video_to_axis_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_video_to_axis_0_0 || ORIG_REF_NAME==ddr_dma_v2_video_to_axis_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_v_gamma_0_0/ddr_dma_v2_v_gamma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_v_gamma_0_0 || ORIG_REF_NAME==ddr_dma_v2_v_gamma_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_v_rgb2ycrcb_0_0/ddr_dma_v2_v_rgb2ycrcb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==ddr_dma_v2_v_rgb2ycrcb_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_hdr_ip_0_0/ddr_dma_v2_hdr_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_hdr_ip_0_0 || ORIG_REF_NAME==ddr_dma_v2_hdr_ip_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_edge_ip_0_0/ddr_dma_v2_edge_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_edge_ip_0_0 || ORIG_REF_NAME==ddr_dma_v2_edge_ip_0_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_0/ddr_dma_v2_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_0 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_0/ddr_dma_v2_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_pc_0 || ORIG_REF_NAME==ddr_dma_v2_auto_pc_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_cc_0/ddr_dma_v2_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_cc_0 || ORIG_REF_NAME==ddr_dma_v2_auto_cc_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_1/ddr_dma_v2_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_1 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_1}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_1/ddr_dma_v2_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_pc_1 || ORIG_REF_NAME==ddr_dma_v2_auto_pc_1}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_2/ddr_dma_v2_auto_ds_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_2 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_2}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_2/ddr_dma_v2_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_pc_2 || ORIG_REF_NAME==ddr_dma_v2_auto_pc_2}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_3/ddr_dma_v2_auto_ds_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_3 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_3}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_3/ddr_dma_v2_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_pc_3 || ORIG_REF_NAME==ddr_dma_v2_auto_pc_3}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_4/ddr_dma_v2_auto_ds_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_4 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_4}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_4/ddr_dma_v2_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_pc_4 || ORIG_REF_NAME==ddr_dma_v2_auto_pc_4}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_5/ddr_dma_v2_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_pc_5 || ORIG_REF_NAME==ddr_dma_v2_auto_pc_5}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_0/ddr_dma_v2_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_0 || ORIG_REF_NAME==ddr_dma_v2_auto_us_0}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_1/ddr_dma_v2_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_1 || ORIG_REF_NAME==ddr_dma_v2_auto_us_1}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_2/ddr_dma_v2_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_2 || ORIG_REF_NAME==ddr_dma_v2_auto_us_2}]

# IP: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_3/ddr_dma_v2_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_3 || ORIG_REF_NAME==ddr_dma_v2_auto_us_3}]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_0/ddr_dma_v2_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_microblaze_0_0 || ORIG_REF_NAME==ddr_dma_v2_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_0/ddr_dma_v2_microblaze_0_0_ooc_debug.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_0/ddr_dma_v2_microblaze_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_v10_0/ddr_dma_v2_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_dlmb_v10_0 || ORIG_REF_NAME==ddr_dma_v2_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_v10_0/ddr_dma_v2_dlmb_v10_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_v10_0/ddr_dma_v2_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_ilmb_v10_0 || ORIG_REF_NAME==ddr_dma_v2_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_v10_0/ddr_dma_v2_ilmb_v10_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_dlmb_bram_if_cntlr_0/ddr_dma_v2_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_ilmb_bram_if_cntlr_0/ddr_dma_v2_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_lmb_bram_0/ddr_dma_v2_lmb_bram_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_intc_0/ddr_dma_v2_microblaze_0_axi_intc_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==ddr_dma_v2_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_intc_0/ddr_dma_v2_microblaze_0_axi_intc_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_microblaze_0_axi_intc_0 || ORIG_REF_NAME==ddr_dma_v2_microblaze_0_axi_intc_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_microblaze_0_axi_intc_0/ddr_dma_v2_microblaze_0_axi_intc_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_mdm_1_0/ddr_dma_v2_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_mdm_1_0 || ORIG_REF_NAME==ddr_dma_v2_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_mdm_1_0/ddr_dma_v2_mdm_1_0_ooc_trace.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_clk_wiz_1_0/ddr_dma_v2_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_clk_wiz_1_0 || ORIG_REF_NAME==ddr_dma_v2_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_clk_wiz_1_0/ddr_dma_v2_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_clk_wiz_1_0 || ORIG_REF_NAME==ddr_dma_v2_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_clk_wiz_1_0/ddr_dma_v2_clk_wiz_1_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_clk_wiz_1_100M_0/ddr_dma_v2_rst_clk_wiz_1_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ddr_dma_v2_rst_clk_wiz_1_100M_0}]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_clk_wiz_1_100M_0/ddr_dma_v2_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ddr_dma_v2_rst_clk_wiz_1_100M_0}]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_clk_wiz_1_100M_0/ddr_dma_v2_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_mig_7series_0_0/ddr_dma_v2_mig_7series_0_0/user_design/constraints/ddr_dma_v2_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_mig_7series_0_0 || ORIG_REF_NAME==ddr_dma_v2_mig_7series_0_0}]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_mig_7series_0_0/ddr_dma_v2_mig_7series_0_0/user_design/constraints/ddr_dma_v2_mig_7series_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_mig_7series_0_0/ddr_dma_v2_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_mig_7series_0_0 || ORIG_REF_NAME==ddr_dma_v2_mig_7series_0_0}]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_uartlite_0_0/ddr_dma_v2_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_uartlite_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_uartlite_0_0/ddr_dma_v2_axi_uartlite_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_uartlite_0_0/ddr_dma_v2_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_uartlite_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_xbar_0/ddr_dma_v2_xbar_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_mig_7series_0_81M_0/ddr_dma_v2_rst_mig_7series_0_81M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==ddr_dma_v2_rst_mig_7series_0_81M_0}]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_mig_7series_0_81M_0/ddr_dma_v2_rst_mig_7series_0_81M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr_dma_v2_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==ddr_dma_v2_rst_mig_7series_0_81M_0}]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_rst_mig_7series_0_81M_0/ddr_dma_v2_rst_mig_7series_0_81M_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_dma_0_0/ddr_dma_v2_axi_dma_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_dma_0_0/ddr_dma_v2_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_dma_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_dma_0_0/ddr_dma_v2_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_dma_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_tft_0_0/ddr_dma_v2_axi_tft_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_tft_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_tft_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_tft_0_0/ddr_dma_v2_axi_tft_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_tft_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_tft_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_tft_0_0/ddr_dma_v2_axi_tft_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_quad_spi_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_quad_spi_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_axi_quad_spi_0_0/ddr_dma_v2_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_axi_quad_spi_0_0 || ORIG_REF_NAME==ddr_dma_v2_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_v_gamma_0_0/ddr_dma_v2_v_gamma_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_v_gamma_0_0 || ORIG_REF_NAME==ddr_dma_v2_v_gamma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_v_gamma_0_0/ddr_dma_v2_v_gamma_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_v_rgb2ycrcb_0_0/ddr_dma_v2_v_rgb2ycrcb_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_v_rgb2ycrcb_0_0 || ORIG_REF_NAME==ddr_dma_v2_v_rgb2ycrcb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_v_rgb2ycrcb_0_0/ddr_dma_v2_v_rgb2ycrcb_0_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_0/ddr_dma_v2_auto_ds_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_0/ddr_dma_v2_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_0 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_0}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_0/ddr_dma_v2_auto_pc_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_cc_0/ddr_dma_v2_auto_cc_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_cc_0/ddr_dma_v2_auto_cc_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_cc_0 || ORIG_REF_NAME==ddr_dma_v2_auto_cc_0}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_1/ddr_dma_v2_auto_ds_1_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_1/ddr_dma_v2_auto_ds_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_1 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_1}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_1/ddr_dma_v2_auto_pc_1_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_2/ddr_dma_v2_auto_ds_2_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_2/ddr_dma_v2_auto_ds_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_2 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_2}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_2/ddr_dma_v2_auto_pc_2_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_3/ddr_dma_v2_auto_ds_3_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_3/ddr_dma_v2_auto_ds_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_3 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_3}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_3/ddr_dma_v2_auto_pc_3_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_4/ddr_dma_v2_auto_ds_4_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_ds_4/ddr_dma_v2_auto_ds_4_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_ds_4 || ORIG_REF_NAME==ddr_dma_v2_auto_ds_4}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_4/ddr_dma_v2_auto_pc_4_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_pc_5/ddr_dma_v2_auto_pc_5_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_0/ddr_dma_v2_auto_us_0_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_0/ddr_dma_v2_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_0 || ORIG_REF_NAME==ddr_dma_v2_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_1/ddr_dma_v2_auto_us_1_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_1/ddr_dma_v2_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_1 || ORIG_REF_NAME==ddr_dma_v2_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_2/ddr_dma_v2_auto_us_2_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_2/ddr_dma_v2_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_2 || ORIG_REF_NAME==ddr_dma_v2_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_3/ddr_dma_v2_auto_us_3_ooc.xdc

# XDC: bd/ddr_dma_v2/ip/ddr_dma_v2_auto_us_3/ddr_dma_v2_auto_us_3_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr_dma_v2_auto_us_3 || ORIG_REF_NAME==ddr_dma_v2_auto_us_3}] {/inst }]/inst ]]

# XDC: bd/ddr_dma_v2/ddr_dma_v2_ooc.xdc
